import React from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
    title: "Terms of Use | ShaatHaTipa",
    description: "Legal Disclaimer and Terms of Use for ShaatHaTipa application.",
};

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl bg-white p-8 rounded-2xl shadow-sm border border-slate-200">

                {/* Back Link */}
                <div className="mb-8">
                    <Link
                        href="/"
                        className="inline-flex items-center text-sm font-medium text-slate-500 hover:text-sky-600 transition-colors"
                    >
                        <ArrowLeft className="w-4 h-4 mr-1" />
                        Back to Home / חזרה לדף הבית
                    </Link>
                </div>

                {/* English Section */}
                <div className="space-y-6 text-slate-900" dir="ltr">
                    <h1 className="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl mb-6">
                        LEGAL DISCLAIMER AND TERMS OF USE
                    </h1>

                    <section>
                        <h2 className="text-lg font-bold mb-2">1. No Medical Advice</h2>
                        <p className="text-slate-700 leading-relaxed">
                            This application ("The App") is a technical tool designed solely to assist users in organizing general medication schedules based on user-selected protocols. The App does NOT provide medical advice, diagnosis, or treatment. The content generated by The App is for informational and educational purposes only.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-2">2. No Doctor-Patient Relationship</h2>
                        <p className="text-slate-700 leading-relaxed">
                            Use of The App does not establish a doctor-patient relationship between the user and the developer, owner, or any affiliated parties. The App is not a medical device and should not be relied upon for critical healthcare decisions.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-2">3. General Protocols Only</h2>
                        <p className="text-slate-700 leading-relaxed">
                            The schedules generated are based on standard, non-personalized protocols. They do not account for individual medical history, allergies, drug interactions, or post-operative complications. Your specific surgeon’s instructions, prescriptions, and discharge papers ALWAYS override any information provided by The App. If there is a discrepancy, follow your surgeon’s orders.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-2">4. No Data Storage</h2>
                        <p className="text-slate-700 leading-relaxed">
                            The App runs locally on your device or in a transient state and does not collect, store, or transmit personally identifiable medical information (PHI) in compliance with privacy standards. You are responsible for maintaining the privacy of your own screen and device.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-2">5. Limitation of Liability</h2>
                        <p className="text-slate-700 leading-relaxed">
                            To the fullest extent permitted by applicable law, the developer and affiliates shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use The App. This includes, but is not limited to, errors in medication timing, dosage confusion, or adverse health outcomes. You assume full responsibility for your medication management.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-2">6. Jurisdiction</h2>
                        <p className="text-slate-700 leading-relaxed">
                            These terms shall be governed by and construed in accordance with the laws of the State of Israel. Any disputes arising from the use of The App shall be subject to the exclusive jurisdiction of the competent courts in Tel Aviv, Israel.
                        </p>
                    </section>
                </div>

                <div className="my-12 h-px bg-slate-200" />

                {/* Hebrew Section */}
                <div className="space-y-6 text-slate-900 text-right" dir="rtl">
                    <h1 className="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl mb-6">
                        כתב ויתור משפטי ותנאי שימוש
                    </h1>

                    <section>
                        <h2 className="text-lg font-bold mb-2">1. היעדר ייעוץ רפואי</h2>
                        <p className="text-slate-700 leading-relaxed">
                            אפליקציה זו ("האפליקציה") הינה כלי טכני שנועד אך ורק לסייע למשתמשים בארגון לוחות זמנים כלליים לנטילת תרופות, על בסיס פרוטוקולים שנבחרו על ידי המשתמש. האפליקציה אינה מספקת ייעוץ רפואי, אבחון או טיפול. התוכן המופק על ידי האפליקציה נועד למטרות מידע והתארגנות בלבד.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-2">2. היעדר יחסי רופא-מטופל</h2>
                        <p className="text-slate-700 leading-relaxed">
                            השימוש באפליקציה אינו יוצר יחסי רופא-מטופל בין המשתמש לבין המפתח, הבעלים או כל צד קשור. האפליקציה אינה מכשור רפואי ואין להסתמך עליה לצורך קבלת החלטות רפואיות קריטיות.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-2">3. פרוטוקולים כלליים בלבד</h2>
                        <p className="text-slate-700 leading-relaxed">
                            לוחות הזמנים המופקים מבוססים על פרוטוקולים סטנדרטיים ואינם מותאמים אישית. הם אינם מביאים בחשבון היסטוריה רפואית אישית, רגישויות, אינטראקציות בין תרופות או סיבוכים לאחר ניתוח. הנחיות המנתח/ת, המרשמים ומכתב השחרור שלך גוברים תמיד על כל מידע המופיע באפליקציה. במקרה של סתירה, יש לפעול לפי הוראות המנתח/ת.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-2">4. היעדר שמירת מידע</h2>
                        <p className="text-slate-700 leading-relaxed">
                            האפליקציה פועלת באופן מקומי או ארעי ואינה אוספת, שומרת או מעבירה מידע רפואי אישי מזהה, זאת בהתאם לסטנדרטים של פרטיות. האחריות על שמירת פרטיות המסך והמכשיר שלך חלה עליך בלבד.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-2">5. הגבלת אחריות</h2>
                        <p className="text-slate-700 leading-relaxed">
                            במידה המקסימלית המותרת על פי דין, המפתח והגורמים הקשורים אליו לא יישאו באחריות לכל נזק ישיר, עקיף, מקרי או תוצאתי הנובע מהשימוש או מחוסר היכולת להשתמש באפליקציה. זאת כולל, בין היתר, טעויות בתזמון נטילת תרופות, בלבול במינונים או תוצאות בריאותיות שליליות. הנך נושא/ת באחריות המלאה לניהול הטיפול התרופתי שלך.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-2">6. סמכות שיפוט</h2>
                        <p className="text-slate-700 leading-relaxed">
                            תנאים אלו כפופים לחוקי מדינת ישראל. כל מחלוקת הנובעת מהשימוש באפליקציה תהיה נתונה לסמכות השיפוט הבלעדית של בתי המשפט המוסמכים בתל אביב-יפו.
                        </p>
                    </section>
                </div>

                <div className="mt-12 text-center text-sm text-slate-400">
                    Last updated: {new Date().toLocaleDateString('en-GB')}
                </div>

            </div>
        </div>
    );
}
