// lib/utils/pdf.ts
// Utility for generating and printing a PDF schedule. Groups dose slots
// by day and time, builds an HTML document, and opens a new window to
// print or save as PDF. Also includes helpers for safe HTML and date formatting.

import { getMedicationColor } from "../theme/medicationColors";
import type { DoseSlot, ProtocolAction } from "../../types/prescription";
import type { ClinicConfig } from "../../config/clinics";

const LABELS = {
  en: {
    day: "Day",
    time: "Time",
    notes: "Notes",
    noDoses: "No doses scheduled for this period.",
    generatedBy: "Generated by ShaatHaTipa",
  },
  he: {
    day: "יום",
    time: "שעה",
    notes: "הערות",
    noDoses: "אין מנות מתוכננות לתקופה זו.",
    generatedBy: "נוצר ע״י שעת הטיפה",
  },
};

// Escape HTML special characters to prevent injection.
function escapeHtml(str: string): string {
  if (!str) return "";
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// Group dose slots by date.
function groupByDate(schedule: DoseSlot[]): { date: string; slots: DoseSlot[] }[] {
  const map = new Map<string, DoseSlot[]>();
  schedule.forEach((slot) => {
    if (!map.has(slot.date)) {
      map.set(slot.date, []);
    }
    map.get(slot.date)!.push(slot);
  });
  return Array.from(map.entries()).map(([date, slots]) => ({ date, slots }));
}

// Group dose slots by time within a date.
function groupByTime(slots: DoseSlot[]): { time: string; slots: DoseSlot[] }[] {
  const map = new Map<string, DoseSlot[]>();
  slots.forEach((slot) => {
    if (!map.has(slot.time)) {
      map.set(slot.time, []);
    }
    map.get(slot.time)!.push(slot);
  });
  return Array.from(map.entries()).map(([time, s]) => ({ time, slots: s }));
}

// Build the printable HTML document for the schedule.
function buildPrintableHtml(
  schedule: DoseSlot[],
  fileName: string,
  clinic?: ClinicConfig | null,
  locale: "en" | "he" = "en",
  customActionLabel?: string,
  manualActions?: ProtocolAction[]
): string {
  const dayGroups = groupByDate(schedule);
  const parts: string[] = [];

  const isRtl = locale === 'he';
  const safeLocale = isRtl ? 'he' : 'en';
  const t = LABELS[safeLocale];

  // Resolve texts
  const clinicName = clinic?.name || "ShaatHaTipa";
  const title = clinic?.copy?.[safeLocale]?.heroTitle
    ? `${clinicName} – ${clinic.copy[safeLocale].heroTitle}`
    : `${clinicName} – Post-surgery schedule`;

  const actionLabel = customActionLabel || clinic?.copy?.[safeLocale]?.actionLabel || (isRtl ? "טיפות" : "Drops");

  // Resolve Logo URL - must be absolute for some browsers/contexts or relative if same origin.
  // We'll use window.location.origin if available to ensure images load in print preview.
  let logoSrc = "";
  if (typeof window !== "undefined" && clinic?.logoUrl) {
    // If it's already absolute (http/https), use it. otherwise preprend origin.
    // Also handle base64 data URIs just in case.
    logoSrc = (clinic.logoUrl.startsWith("http") || clinic.logoUrl.startsWith("data:"))
      ? clinic.logoUrl
      : `${window.location.origin}${clinic.logoUrl}`;
  }

  parts.push(
    `<!DOCTYPE html>
    <html dir="${isRtl ? "rtl" : "ltr"}" lang="${safeLocale}">
    <head>
      <meta charSet="utf-8">
      <title>${escapeHtml(title)}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 40px; /* More margin for print */
          background: #ffffff;
          color: #0f172a;
          direction: ${isRtl ? "rtl" : "ltr"};
        }
        .header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          margin-bottom: 24px;
          border-bottom: 2px solid #e2e8f0;
          padding-bottom: 16px;
        }
        .logo {
          max-height: 60px;
          max-width: 200px;
          object-fit: contain;
        }
        h1 { font-size: 24px; margin: 0; color: #1e293b; }
        h2 { font-size: 16px; margin: 24px 0 12px; color: #334155; border-bottom: 1px solid #f1f5f9; padding-bottom: 4px; }
        
        table { width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 13px; }
        th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: ${isRtl ? "right" : "left"}; }
        th { background: #f8fafc; color: #475569; font-weight: 600; }
        
        .chip {
          display: inline-block;
          margin: 2px;
          padding: 3px 8px;
          border-radius: 999px;
          border: 1px solid;
          line-height: 1.2;
          font-weight: 500;
          font-size: 12px;
        }
        
        @media print {
          body { margin: 0; padding: 20px; }
          .no-print { display: none; }
          /* Ensure colors print */
          -webkit-print-color-adjust: exact !important;
          print-color-adjust: exact !important;
        }
      </style>
    </head>
    <body>`
  );

  // Header
  parts.push(`<div class="header">`);

  if (logoSrc) {
    parts.push(`<img src="${escapeHtml(logoSrc)}" alt="Logo" class="logo" />`);
  }

  parts.push(`<div>
    <h1>${escapeHtml(title)}</h1>
    <div style="font-size: 12px; color: #64748b; margin-top: 4px;">${escapeHtml(fileName.replace('.pdf', ''))}</div>
  </div>`);

  parts.push(`</div>`); // End header

  if (dayGroups.length === 0) {
    if (manualActions && manualActions.length > 0) {
      parts.push(`<h2>${isRtl ? "הנחיות לטיפול" : "Treatment Instructions"}</h2>`);
      parts.push(`<table><thead><tr>
            <th style="width: 30%">${escapeHtml(customActionLabel || (isRtl ? "טיפול" : "Treatment"))}</th>
            <th style="width: 70%">${escapeHtml(t.notes)}</th>
        </tr></thead><tbody>`);

      manualActions.forEach(action => {
        parts.push(`<tr>
                <td><strong>${escapeHtml(action.name)}</strong></td>
                <td>${escapeHtml(action.notes || "")}</td>
            </tr>`);
      });
      parts.push("</tbody></table>");
    } else {
      parts.push(`<p style="text-align:center;color:#64748b;margin-top:40px;">${escapeHtml(t.noDoses)}</p>`);
    }
  } else {
    dayGroups.forEach((day) => {
      const timeGroups = groupByTime(day.slots);
      parts.push(`<h2>${escapeHtml(t.day)} ${day.slots[0].dayIndex} • ${escapeHtml(day.date)}</h2>`);
      parts.push(`<table><thead><tr>
        <th style="width: 15%">${escapeHtml(t.time)}</th>
        <th style="width: 50%">${escapeHtml(actionLabel)}</th>
        <th style="width: 35%">${escapeHtml(t.notes)}</th>
      </tr></thead><tbody>`);

      timeGroups.forEach((tg) => {
        const medsHtml = tg.slots
          .map((s) => {
            // Use medicationColor from slot (assigned by schedule builder)
            // Fallback to getMedicationColor for backward compatibility
            const color = s.medicationColor || getMedicationColor(s.medicationName, s.medicationId) || "#0f172a";
            // Use lighter background for print legibility
            return `<span class="chip" style="color:${color};border-color:${color}40;background-color:#ffffff;">${escapeHtml(
              s.medicationName,
            )}</span>`;
          })
          .join(" ");

        const notesSet = new Set(
          tg.slots
            .map((s) => s.notes?.trim())
            .filter((n): n is string => !!n),
        );
        const notes = notesSet.size > 0 ? Array.from(notesSet).map(escapeHtml).join(" • ") : "";

        parts.push(
          `<tr>
            <td>${escapeHtml(tg.time)}</td>
            <td>${medsHtml}</td>
            <td>${notes}</td>
          </tr>`
        );
      });
      parts.push("</tbody></table>");
    });
  }

  // Footer
  parts.push(`<div style="margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 12px; font-size: 10px; color: #94a3b8; text-align: center;">
    ${escapeHtml(t.generatedBy)}
  </div>`);

  parts.push("</body></html>");
  return parts.join("");
}

/**
 * Open a new window and print the schedule as a PDF.
 * @param schedule - Array of dose slots to export
 * @param fileName - The desired filename (without extension)
 * @param clinic - Clinic config for branding
 * @param locale - Current locale ('en' or 'he')
 * @param actionLabel - Optional override label for the action column
 */
export function openSchedulePdf(
  schedule: DoseSlot[],
  fileName: string,
  clinic: ClinicConfig | null | undefined,
  locale: string = 'en',
  actionLabel?: string,
  manualActions?: ProtocolAction[]
): void {
  if (typeof window === "undefined") return;

  // Normalize locale to supported types
  const safeLocale = (locale === 'he' || locale === 'en') ? locale : 'en';

  const html = buildPrintableHtml(schedule, fileName, clinic, safeLocale, actionLabel, manualActions);
  const newWindow = window.open("", "_blank");
  if (!newWindow) {
    alert("Please allow popups to download the PDF.");
    return;
  }

  newWindow.document.open();
  newWindow.document.write(html);
  newWindow.document.close();

  // Delay printing slightly to allow images and styles to load.
  setTimeout(() => {
    newWindow.focus();
    newWindow.print();
  }, 800);
}
